name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore  ./PYP_Pre_Assignment/PYP_Pre_Assignment.sln
    - name: Build
      run: dotnet build --no-restore  ./PYP_Pre_Assignment/PYP_Pre_Assignment.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./PYP_Pre_Assignment/PYP_Pre_Assignment.sln
